spring:
  application:
    name: wcc-backend

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
  paths-to-match: /api/**,

surrealdb:
  url:http://localhost:8000/sql: