version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9005:9005"
    depends_on:
      - surrealdb
    environment:
      SPRING_DATASOURCE_URL: "jdbc:surrealdb://surrealdb:8000/namespace/database"
      SPRING_DATASOURCE_USERNAME: "wcc-backend"
      SPRING_DATASOURCE_PASSWORD: "wcc-platform"

  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - "8000:8000"
    environment:
      SURREAL_USER: "wcc-backend"
      SURREAL_PASS: "wcc-platform"
